### ISSUE TITLE
GET recipe By Id

### ISSUE THREAD

**Issue by KB-HH** [neuefische/ffm-java-23-1-team-project-2#33]
**As a User** 
**I need** to search for recipes in my library
**to be able to** quickly find a specific recipe

#### Description
Implement a search feature that allows users to search for recipes based on criteria such as title, description, or genre.

#### Acceptance Criteria

- [ ] Create a GET "/api/recipes/{id}" endpoint to fetch the restaurant specified by the id.
- [ ] Display all informations given from the backend on a extra Route for each restaurant "/recipes/:id
- [ ] When clicking a recipe in the list view or navigating directly via the url the details page should be shown

#### Tasks

- [ ] Implement a component that shows the recipe Details when you click on recipe in the list view
- [ ] Create a GET request to retrieve the recipe data from the backend (Get By Id).
- [ ] Implement Unit and Integration Test.
- [ ] add some styling
